// generated by enums.ts, do not edit

export const allocationValues = ['None', 'Ship', 'Villa'] as const
export type Allocation = (typeof allocationValues)[number]

export const buildingKindValues = [
  'Aqueduct',
  'City Watch',
  'Harbour',
  'Marsh',
  'Military',
  'Monument',
  'Production',
  'Public Service',
  'Residence',
  'Road',
] as const
export type BuildingKind = (typeof buildingKindValues)[number]

export const buildingTypeValues = [
  'Factory',
  'Logistic',
  'Other',
  'Public',
  'Residence',
  'Warehouse',
] as const
export type BuildingType = (typeof buildingTypeValues)[number]

export const effectScopeValues = [
  'Area',
  'AreasInMeta',
  'AreasInSession',
  'Local',
  'Meta',
  'ModuleOwner',
  'ObjectsInArea',
  'ObjectsInMeta',
  'ObjectsInSession',
  'Radius',
  'StreetDistance',
] as const
export type EffectScope = (typeof effectScopeValues)[number]

export const itemTypeValues = [
  'Captains',
  'NonSocketable',
  'None',
  'Specialist',
] as const
export type ItemType = (typeof itemTypeValues)[number]

export const needCategoryValues = [
  'Culture',
  'Fashion',
  'Food',
  'Household',
  'Public',
  'Wonders',
] as const
export type NeedCategory = (typeof needCategoryValues)[number]

export const nicheValues = [
  'Agriculture',
  'Culture',
  'Diplomacy',
  'Economy',
  'Finance',
  'Military',
  'Nautics',
  'None',
  'Religion',
  'Research',
] as const
export type Niche = (typeof nicheValues)[number]

export const nodeTypeValues = [
  'ComplexCombination',
  'Decision',
  'DecisionRoot',
  'DenyAndExit',
  'Exit',
  'Function',
  'FunctionImmediate',
  'Loop',
  'Objective',
  'QuestLine',
  'Sequence',
  'SequenceCharNotif',
  'Starter',
  'StateChecker',
  'StoryLine',
  'Success',
] as const
export type NodeType = (typeof nodeTypeValues)[number]

export const optionCategoryValues = ['None', 'Rebellion'] as const
export type OptionCategory = (typeof optionCategoryValues)[number]

export const questCategoryValues = [
  'Campaign',
  'Contracts',
  'Quests',
  'Tutorials',
] as const
export type QuestCategory = (typeof questCategoryValues)[number]

export const rarityValues = [
  'Common',
  'Epic',
  'Legendary',
  'Mythic',
  'Quest',
  'Rare',
  'Uncommon',
  'Unique',
] as const
export type Rarity = (typeof rarityValues)[number]

export const sourceCategoryValues = [
  'Adjacency',
  'Aqueduct',
  'Assembly',
  'Diplomacy',
  'Festival',
  'Generic',
  'Institution',
  'Item',
  'MajorIncident',
  'Religion',
  'Tech',
  'Threat',
  'Volcano',
  'Wonder',
] as const
export type SourceCategory = (typeof sourceCategoryValues)[number]

export const storageLevelValues = ['Area', 'Building', 'Meta'] as const
export type StorageLevel = (typeof storageLevelValues)[number]

export const storylineSystemValues = [
  'Contracts',
  'GovernorDecisions',
  'Quests',
] as const
export type StorylineSystem = (typeof storylineSystemValues)[number]

export const transportTypeValues = [
  'Intermediate',
  'Material',
  'Needs',
  'Raw',
] as const
export type TransportType = (typeof transportTypeValues)[number]

export const attributeValues = [
  'Population',
  'Money',
  'Happiness',
  'Belief',
  'Knowledge',
  'Prestige',
  'Health',
  'FireSafety',
  'AdditionalNeedAttributes',
] as const
export type Attribute = (typeof attributeValues)[number]

export const langValues = ['en', 'de'] as const
export type Lang = (typeof langValues)[number]

/** ISO code -> name of the game's texts file / lang table row */
export const langNames = {
  de: 'german',
  en: 'english',
} as const satisfies Record<Lang, string>
