// generated by enums.ts, do not edit

export const allocationValues = ['None', 'Ship', 'Villa'] as const
export type Allocation = (typeof allocationValues)[number]

export const buildingKindValues = [
  'Aqueduct',
  'City Watch',
  'Harbour',
  'Marsh',
  'Military',
  'Monument',
  'Production',
  'Public Service',
  'Residence',
  'Road',
] as const
export type BuildingKind = (typeof buildingKindValues)[number]

export const buildingTypeValues = [
  'Factory',
  'Logistic',
  'Other',
  'Public',
  'Residence',
  'Warehouse',
] as const
export type BuildingType = (typeof buildingTypeValues)[number]

export const chainTypeValues = [
  'Consumer',
  'Harbour',
  'Material',
  'Military',
] as const
export type ChainType = (typeof chainTypeValues)[number]

export const conditionTemplateValues = [
  'ConditionActiveEmperor',
  'ConditionActiveSession',
  'ConditionAlwaysFalse',
  'ConditionAlwaysTrue',
  'ConditionAreaOwnedByHuman',
  'ConditionCityStatus',
  'ConditionCompareVariable',
  'ConditionDiplomacyState',
  'ConditionDominantPatron',
  'ConditionEmperorRelation',
  'ConditionFestivalActive',
  'ConditionInStorage',
  'ConditionIsCampaign',
  'ConditionIsDLCActive',
  'ConditionIsDiscovered',
  'ConditionIsParticipantInGame',
  'ConditionIsProducible',
  'ConditionItemUsed',
  'ConditionMonumentEventActive',
  'ConditionNeedAttributeCounter',
  'ConditionObjectCount',
  'ConditionPlayerCounter',
  'ConditionRaceOutcome',
  'ConditionReligion',
  'ConditionTechResearched',
  'ConditionTimer',
  'ConditionTradeRouteCount',
  'ConditionUnlocked',
  'ConditionVolcanoPhaseActive',
  'ConditionWarState',
] as const
export type ConditionTemplate = (typeof conditionTemplateValues)[number]

export const effectScopeValues = [
  'Area',
  'AreasInMeta',
  'AreasInSession',
  'Local',
  'Meta',
  'ModuleOwner',
  'ObjectsInArea',
  'ObjectsInMeta',
  'ObjectsInSession',
  'Radius',
  'StreetDistance',
] as const
export type EffectScope = (typeof effectScopeValues)[number]

export const itemSourceKindValues = [
  'contract',
  'defeated',
  'festival',
  'quest',
  'shipDrop',
  'storyline',
  'tech',
  'trader',
  'visitor',
] as const
export type ItemSourceKind = (typeof itemSourceKindValues)[number]

export const itemTypeValues = [
  'Captains',
  'NonSocketable',
  'None',
  'Specialist',
] as const
export type ItemType = (typeof itemTypeValues)[number]

export const needCategoryValues = [
  'Culture',
  'Fashion',
  'Food',
  'Household',
  'Public',
  'Wonders',
] as const
export type NeedCategory = (typeof needCategoryValues)[number]

export const nicheValues = [
  'Agriculture',
  'Culture',
  'Diplomacy',
  'Economy',
  'Finance',
  'Military',
  'Nautics',
  'None',
  'Religion',
  'Research',
] as const
export type Niche = (typeof nicheValues)[number]

export const nodeTypeValues = [
  'ComplexCombination',
  'Decision',
  'DecisionRoot',
  'DenyAndExit',
  'Exit',
  'Function',
  'FunctionImmediate',
  'Loop',
  'Objective',
  'QuestLine',
  'Sequence',
  'SequenceCharNotif',
  'Starter',
  'StateChecker',
  'StoryLine',
  'Success',
] as const
export type NodeType = (typeof nodeTypeValues)[number]

export const optionCategoryValues = ['None', 'Rebellion'] as const
export type OptionCategory = (typeof optionCategoryValues)[number]

export const participantKindValues = [
  'Emperor',
  'Pirate',
  'Rival',
  'Trader',
] as const
export type ParticipantKind = (typeof participantKindValues)[number]

export const productKindValues = [
  'Good',
  'Meta',
  'Service',
  'Workforce',
] as const
export type ProductKind = (typeof productKindValues)[number]

export const questCategoryValues = [
  'Campaign',
  'Contracts',
  'Quests',
  'Tutorials',
] as const
export type QuestCategory = (typeof questCategoryValues)[number]

export const rarityValues = [
  'Common',
  'Epic',
  'Legendary',
  'Mythic',
  'Quest',
  'Rare',
  'Uncommon',
  'Unique',
] as const
export type Rarity = (typeof rarityValues)[number]

export const sourceCategoryValues = [
  'Adjacency',
  'Aqueduct',
  'Assembly',
  'Diplomacy',
  'Festival',
  'Generic',
  'Institution',
  'Item',
  'MajorIncident',
  'Religion',
  'Tech',
  'Threat',
  'Volcano',
  'Wonder',
] as const
export type SourceCategory = (typeof sourceCategoryValues)[number]

export const storylineSystemValues = [
  'Contracts',
  'GovernorDecisions',
  'Quests',
] as const
export type StorylineSystem = (typeof storylineSystemValues)[number]

export const attributeValues = [
  'Population',
  'Money',
  'Happiness',
  'Belief',
  'Knowledge',
  'Prestige',
  'Health',
  'FireSafety',
  'AdditionalNeedAttributes',
] as const
export type Attribute = (typeof attributeValues)[number]

export const langValues = ['en', 'de'] as const
export type Lang = (typeof langValues)[number]

export const dlcValues = [
  'DLC01_Prophecies_of_Ash',
  'DLC02_The_Hippodrome',
  'DLC03_Dawn_of_Delta',
] as const
export type Dlc = (typeof dlcValues)[number]

export const regionValues = ['Roman', 'Celtic', 'Egyptian'] as const
export type Region = (typeof regionValues)[number]

export const buildingCategoryValues = [
  'Amenity',
  'Arable Farm',
  'Armoury',
  'Artisanal Studio',
  'Barterer',
  'Celtic Residence',
  'City Watch',
  'Clothier',
  'Defensive Building',
  'Emperor Representative',
  'Extractor',
  'Fishery',
  'Forest Camp',
  'Free Trader',
  'Gatherer',
  'Harbour Building',
  'Hunting Cabin',
  'Infrastructure Building',
  'Kitchen',
  'Livestock Farm',
  'Marvel',
  'Mine',
  'Monument— Marvel',
  'Ornamental Road',
  'Pit',
  'Plantation',
  'Public Service',
  'Quarry',
  'Recruitment Building',
  'Refinery',
  'Road',
  'Roman Residence',
  'Romano-Celtic Residence',
  'Shrine',
  'Smelter',
  'Specialist Building',
  'Upholsterer',
  'Victualler',
  'Workshop',
] as const
export type BuildingCategory = (typeof buildingCategoryValues)[number]

/** ISO code -> name of the game's texts file / lang table row */
export const langNames = {
  de: 'german',
  en: 'english',
} as const satisfies Record<Lang, string>
