// generated by enums.ts, do not edit

export const allocationValues = ['None', 'Ship', 'Villa'] as const
export type Allocation = (typeof allocationValues)[number]

export const categoryKindValues = ['menu', 'product'] as const
export type CategoryKind = (typeof categoryKindValues)[number]

export const conditionTemplateValues = [
  'ConditionActiveEmperor',
  'ConditionActiveIncidentCount',
  'ConditionActiveSession',
  'ConditionAlwaysFalse',
  'ConditionAlwaysTrue',
  'ConditionAreaOwnedByHuman',
  'ConditionCityStatus',
  'ConditionCompareVariable',
  'ConditionDiplomacyState',
  'ConditionDominantPatron',
  'ConditionEmperorRelation',
  'ConditionFestivalActive',
  'ConditionInStorage',
  'ConditionIsCampaign',
  'ConditionIsDLCActive',
  'ConditionIsDiscovered',
  'ConditionIsMaleProtagonist',
  'ConditionIsParticipantInGame',
  'ConditionIsProducible',
  'ConditionItemRacerAttribute',
  'ConditionItemUsed',
  'ConditionMonumentEventActive',
  'ConditionNeedAttributeCounter',
  'ConditionNeedCategoryFulfillment',
  'ConditionObjectCount',
  'ConditionObjectPosition',
  'ConditionPlayerCounter',
  'ConditionProductCapacityReached',
  'ConditionRaceOutcome',
  'ConditionReligion',
  'ConditionTechResearched',
  'ConditionTimer',
  'ConditionTradeRouteCount',
  'ConditionUnlocked',
  'ConditionVolcanoPhaseActive',
  'ConditionWarState',
] as const
export type ConditionTemplate = (typeof conditionTemplateValues)[number]

export const itemSourceKindValues = [
  'contract',
  'defeated',
  'festival',
  'quest',
  'shipDrop',
  'storyline',
  'tech',
  'trader',
  'visitor',
] as const
export type ItemSourceKind = (typeof itemSourceKindValues)[number]

export const labelKindValues = [
  'allocation',
  'attribute',
  'diplomacy',
  'incident',
  'modifier',
  'niche',
  'racer_attribute',
  'rarity',
  'reputation',
] as const
export type LabelKind = (typeof labelKindValues)[number]

export const nicheValues = [
  'Agriculture',
  'Culture',
  'Diplomacy',
  'Economy',
  'Finance',
  'Military',
  'Nautics',
  'None',
  'Religion',
  'Research',
] as const
export type Niche = (typeof nicheValues)[number]

export const racerAttributeValues = [
  'Boost',
  'Consistency',
  'Speed',
  'Stamina',
] as const
export type RacerAttribute = (typeof racerAttributeValues)[number]

export const rarityValues = [
  'Common',
  'Epic',
  'Legendary',
  'Mythic',
  'Quest',
  'Rare',
  'Unique',
] as const
export type Rarity = (typeof rarityValues)[number]

export const subConditionOrderValues = [
  'Linear',
  'MutuallyExclusive',
  'Parallel',
] as const
export type SubConditionOrder = (typeof subConditionOrderValues)[number]

export const variableOperationValues = [
  'Add',
  'Multiply',
  'Set',
  'Subtract',
] as const
export type VariableOperation = (typeof variableOperationValues)[number]

export const attributeValues = [
  'Population',
  'Money',
  'Happiness',
  'Belief',
  'Knowledge',
  'Prestige',
  'Health',
  'FireSafety',
] as const
export type Attribute = (typeof attributeValues)[number]

export const langValues = [
  'en',
  'de',
  'pt-BR',
  'fr',
  'it',
  'ja',
  'ko',
  'pl',
  'ru',
  'zh-Hans',
  'es',
  'zh-Hant',
] as const
export type Lang = (typeof langValues)[number]

export const dlcValues = [
  'DLC01_Prophecies_of_Ash',
  'DLC02_The_Hippodrome',
] as const
export type Dlc = (typeof dlcValues)[number]

export const regionValues = ['Roman', 'Celtic'] as const
export type Region = (typeof regionValues)[number]

/** ISO code -> name of the game's texts file / lang table row */
export const langNames = {
  de: 'german',
  en: 'english',
  es: 'spanish',
  fr: 'french',
  it: 'italian',
  ja: 'japanese',
  ko: 'korean',
  pl: 'polish',
  'pt-BR': 'brazilian',
  ru: 'russian',
  'zh-Hans': 'simplified_chinese',
  'zh-Hant': 'traditional_chinese',
} as const satisfies Record<Lang, string>
