// Generates src/enums.ts from the enum_value, attribute and lang tables. Run via `bun run pull`.

import { Database } from 'bun:sqlite'
import { writeFileSync } from 'node:fs'

const db = new Database('anno.sqlite', { readonly: true })

function pascal(name: string) {
  return name.replace(/(^|_)(\w)/g, (_, __, c: string) => c.toUpperCase())
}

function camel(name: string) {
  const p = pascal(name)
  return p.charAt(0).toLowerCase() + p.slice(1)
}

function block(name: string, values: Array<string>) {
  const type = pascal(name)
  const list = values.map((v) => `'${v}'`).join(', ')
  const ident = `${camel(name)}Values`
  return `export const ${ident} = [${list}] as const\nexport type ${type} = (typeof ${ident})[number]\n`
}

const enums = db
  .query<{ name: string; list: string }, []>(
    "select name, group_concat(value, '|') as list from enum_value group by name order by name",
  )
  .all()
  .map((row) => block(row.name, row.list.split('|')))

const attributes = db
  .query<{ key: string }, []>('select key from attribute order by id')
  .all()
// the game only names languages (texts_<name>.xml); ISO codes are ours
const langCodes: Record<string, string> = {
  brazilian: 'pt-BR',
  english: 'en',
  french: 'fr',
  german: 'de',
  italian: 'it',
  japanese: 'ja',
  korean: 'ko',
  polish: 'pl',
  russian: 'ru',
  simplified_chinese: 'zh-Hans',
  spanish: 'es',
  traditional_chinese: 'zh-Hant',
}
const langs = db
  .query<{ code: string }, []>('select code from lang order by id')
  .all()
  .map((l) => {
    const code = langCodes[l.code]
    if (!code) {
      throw new Error(`no ISO code for game language ${l.code}`)
    }
    return { code, name: l.code }
  })
const langNames = langs.map((l) => `  '${l.code}': '${l.name}',`).join('\n')

const out = [
  '// generated by enums.ts, do not edit',
  '',
  ...enums,
  block(
    'attribute',
    attributes.map((a) => a.key),
  ),
  block(
    'lang',
    langs.map((l) => l.code),
  ),
  `/** ISO code -> name of the game's texts file / lang table row */\nexport const langNames = {\n${langNames}\n} as const satisfies Record<Lang, string>\n`,
]
writeFileSync('src/enums.ts', out.join('\n'))
