// Generates src/enums.ts from the enum_value, attribute and lang tables and types the matching
// text columns in the pulled src/schema.ts as `text({ enum })`. Run via `bun run pull`.

import { Database } from 'bun:sqlite'
import { readFileSync, writeFileSync } from 'node:fs'

const db = new Database('anno.sqlite', {
  readonly: true,
})

function pascal(name: string) {
  return name.replace(/(^|_)(\w)/g, (_, __, c: string) => c.toUpperCase())
}

function camel(name: string) {
  const p = pascal(name)
  return p.charAt(0).toLowerCase() + p.slice(1)
}

function block(name: string, values: Array<string>) {
  const type = pascal(name)
  const list = values.map((v) => `'${v}'`).join(', ')
  const ident = `${camel(name)}Values`
  return `export const ${ident} = [${list}] as const\nexport type ${type} = (typeof ${ident})[number]\n`
}

const enums = db
  .query<
    {
      name: string
      list: string
    },
    []
  >(
    "select name, group_concat(value, '|') as list from enum_value group by name order by name",
  )
  .all()
  .map((row) => block(row.name, row.list.split('|')))

const attributes = db
  .query<
    {
      key: string
    },
    []
  >('select key from attribute order by id')
  .all()
// the game only names languages (texts_<name>.xml); ISO codes are ours
const langCodes: Record<string, string> = {
  brazilian: 'pt-BR',
  english: 'en',
  french: 'fr',
  german: 'de',
  italian: 'it',
  japanese: 'ja',
  korean: 'ko',
  polish: 'pl',
  russian: 'ru',
  simplified_chinese: 'zh-Hans',
  spanish: 'es',
  traditional_chinese: 'zh-Hant',
}
const langs = db
  .query<
    {
      code: string
    },
    []
  >('select code from lang order by id')
  .all()
  .map((l) => {
    const code = langCodes[l.code]
    if (!code) {
      throw new Error(`no ISO code for game language ${l.code}`)
    }
    return {
      code,
      name: l.code,
    }
  })
// region keys (Roman, Celtic, Egyptian); names are display text and may be localized
const regions = db
  .query<
    {
      key: string
    },
    []
  >('select key from region order by id')
  .all()
const dlcs = db
  .query<{ key: string }, []>(
    'select distinct key from dlc where key is not null order by key',
  )
  .all()
const langNames = langs.map((l) => `  '${l.code}': '${l.name}',`).join('\n')

const out = [
  '// generated by enums.ts, do not edit',
  '',
  ...enums,
  block(
    'attribute',
    attributes.map((a) => a.key),
  ),
  block(
    'lang',
    langs.map((l) => l.code),
  ),
  block(
    'dlc',
    dlcs.map((d) => d.key),
  ),
  block(
    'region',
    regions.map((r) => r.key),
  ),
  `/** ISO code -> name of the game's texts file / lang table row */\nexport const langNames = {\n${langNames}\n} as const satisfies Record<Lang, string>\n`,
]
writeFileSync('src/enums.ts', out.join('\n'))

// schema table -> column -> enum_value name (the transformer's `self.enum(name, …)` call sites)
// plus the attribute table, whose keys are enumerated above
const columnEnums: Record<string, Record<string, string>> = {
  attribute: {
    key: 'attribute',
  },
  buff: {
    sourceCategory: 'source_category',
  },
  building: {
    kind: 'building_kind',
    type: 'building_type',
  },
  dlc: {
    key: 'dlc',
  },
  effect: {
    scope: 'effect_scope',
    sourceCategory: 'source_category',
  },
  item: {
    allocation: 'allocation',
    niche: 'niche',
    rarity: 'rarity',
    type: 'item_type',
  },
  need: {
    category: 'need_category',
  },
  product: {
    storageLevel: 'storage_level',
    transportType: 'transport_type',
  },
  quest: {
    category: 'quest_category',
  },
  questNode: {
    type: 'node_type',
  },
  questOption: {
    category: 'option_category',
  },
  region: {
    key: 'region',
  },
  storyline: {
    system: 'storyline_system',
  },
}
let schema = readFileSync('src/schema.ts', 'utf8')
if (schema.includes("from './enums'")) {
  throw new Error('src/schema.ts is already typed; run `bun run pull` instead')
}
const imports = new Set<string>()
for (const [table, cols] of Object.entries(columnEnums)) {
  const start = schema.indexOf(`export const ${table} = sqliteTable(`)
  const end = schema.indexOf('\nexport const ', start + 1)
  if (start < 0) {
    throw new Error(`no table ${table} in schema`)
  }
  let body = schema.slice(start, end)
  for (const [col, name] of Object.entries(cols)) {
    const ident = `${camel(name)}Values`
    const re = new RegExp(`(\\b${col}: text\\()([^)]*)\\)`)
    if (!re.test(body)) {
      throw new Error(`no text column ${table}.${col} in schema`)
    }
    body = body.replace(
      re,
      (_, head: string, args: string) =>
        `${head}${args ? `${args}, ` : ''}{ enum: ${ident} })`,
    )
    imports.add(ident)
  }
  schema = schema.slice(0, start) + body + schema.slice(end)
}
schema = `import { ${[...imports]
  .sort()
  .join(', ')} } from './enums'\n${schema}`
writeFileSync('src/schema.ts', schema)
